
  
version: '3.7'
services:
  trino-coordinator:
    image: 'trinodb/trino:latest'
    hostname: trino-coordinator
    ports:
      - '8080:8080'
    volumes:
      - ./etc:/etc/trino
    networks:
      - trino-network

  es01:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.11.1'
    hostname: es01
    container_name: es01
    ports:
      - '9200:9200'
    volumes:
      - data01:/usr/share/elasticsearch/data
    environment:     
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - ELASTIC_USERNAME=elastic  
      - ELASTIC_PASSWORD=changeme
      - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - trino-network

volumes:
  data01:
    driver: local

networks:
  trino-network:
    driver: bridge
